### ISSUE TITLE
Infinite scroller did not have a scrollbar - issue fixed (In Vuetify) 

### ISSUE THREAD

**Issue by GeorgeZoum** [legeneek/vue-infinite-list#1]
Fixed the infinite scrollbar not having a scrollbar issue with the help of custom scrollbars 

[https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp]

Use the 

/*_ width */
::-webkit-scrollbar {
    width: 10px;
}

/* Track */
::-webkit-scrollbar-track {
    background: #f1f1f1; 
}

/* Handle */
::-webkit-scrollbar-thumb {
    background: #888; 
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
    background: #555; 
}

**Comment by legeneek** [comment]
In latest chrome or safari, the scrollbar only appear when you scroll the page. This is browser behavior.  It works fine for me.
If this isn't your concern, maybe Vuetify's style make the scrollbar disappear. Haven't used it with Vuetify yet.
